# -*- coding: utf-8 -*-
"""Speech_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoDMMRWJWUdzwsJd4EnXTJOd2PYmQ2Uh
"""

!pip install SpeechRecognition pydub requests
import io
import requests
import speech_recognition as sr
from pydub import AudioSegment

def transcribe_audio_from_url(audio_url):
    """
    Downloads an audio file into memory from a URL and transcribes it.
    Works perfectly inside Google Colab environments.
    """
    recognizer = sr.Recognizer()

    try:
        print(f"🌐 Fetching audio from URL...")
        # Send a network request to grab the audio file bytes
        # Add a User-Agent header to mimic a web browser
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
        response = requests.get(audio_url, timeout=20, headers=headers)
        response.raise_for_status()

        # Convert raw network bytes into an in-memory file stream
        audio_bytes = io.BytesIO(response.content)

        # Check format based on URL string hint
        is_wav = audio_url.lower().endswith('.wav')
        file_format = "wav" if is_wav else "mp3"

        print(f"🔄 Processing {file_format.upper()} audio data stream...")
        sound = AudioSegment.from_file(audio_bytes, format=file_format)

        # Export to a WAV buffer byte stream (SpeechRecognition library requirement)
        wav_buffer = io.BytesIO()
        sound.export(wav_buffer, format="wav")
        wav_buffer.seek(0)

        # Load into the Speech-to-Text engine
        with sr.AudioFile(wav_buffer) as source:
            recognizer.adjust_for_ambient_noise(source, duration=0.5)
            audio_data = recognizer.record(source)

        print("🤖 Transcribing speech text using Google API...")
        text = recognizer.recognize_google(audio_data)
        return text

    except requests.exceptions.RequestException as req_err:
        return f"❌ Network Error: Unable to fetch audio from the URL ({req_err})"
    except sr.UnknownValueError:
        return "❌ Error: Speech recognition engine could not understand the audio words."
    except sr.RequestError as e:
        return f"❌ Service Error: Cloud transcription request failed; {e}"
    except Exception as e:
        return f"❌ Unexpected Error: {e}"

# --- Colab Execution ---
if __name__ == "__main__":
    print("="*60)
    print("       CODTECH INTERNSHIP - SPEECH RECOGNITION SYSTEM       ")
    print("="*60)

    # Using the direct open-speech WAV repository URL
    target_url = "https://www.voiptroubleshooter.com/open_speech/american/OSR_us_000_0010_8k.wav"

    # Run the stream processing and print the final output
    transcription = transcribe_audio_from_url(target_url)

    print("\n" + "="*60)
    print("✨ FINAL TRANSCRIPTION OUTPUT ✨")
    print("="*60)
    print(transcription)
    print("="*60)